language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install coverage nose coveralls
  - pip install .

script: nosetests --with-coverage --cover-package=amocrm

after_success:
  - coveralls
